### ISSUE TITLE
MySQL :: Feature request

### ISSUE THREAD

**Issue by ghost** [ThymonA/NetCoreTemplate#2]
Hi @ThymonA,

Requesting feature MySQL as database option.

```
"ConnectionStrings": {
    "DefaultConnection": ""
},
"NetCoreTemplate": {
    "DatabaseProvider": "MySQL"
}
```

**Comment by ThymonA** [comment]
Hi @nicotravassos 

I'm adding support for MySQL to this project.

**Comment by ghost** [comment]
Thank you @ThymonA.

**Comment by ghost** [comment]
@ThymonA Would it be possible for you implement this feature request soon as my server is running MySQL.

**Comment by ThymonA** [comment]
@nicotravassos I implemented the feature with support for MySQL as database provider. I had to remove existing migrations to make the project suitable for different types of database providers. You also had other feature requirements and I will pick them up this weekend.

**Comment by ghost** [comment]
Thank you @ThymonA
